// Regenerates src/fixtures/unsigned-credential.task3.json — the ONE real,
// unsigned demo credential this package ships. Run with `bun run build-fixture`.
//
// The settled task this credential describes is real: task 3's
// `auto_resolve_dispute` on the Guild's PULL escrow component, settled on
// mainnet 2026-08-26. Every field below traces to a specific line in
// docs/PROJECT-STATE.md (cited inline) — this script does not invent
// numbers, it assembles ones already committed to the repo's own source of
// truth. The one thing it CANNOT get from docs is state_version, which only
// a live Gateway read can supply — see README.md "Fixture provenance" for
// why that read currently fails (the mainnet halt) and what this script
// does about it (nothing clever: `buildCredentialFromReceipt` already
// degrades to `state_version: null` on a Gateway failure, and that is
// exactly what gets committed).

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { buildCredentialFromReceipt, DEFAULT_GATEWAY_URL } from './build-from-receipt.js';
import { publicKeyToDidKey } from './did-key.js';
import { generateThrowawaySigningKey } from './sign.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// docs/PROJECT-STATE.md:6407 (leg table) + :6398-6426 (narrative + conservation math).
const SETTLEMENT_TX = 'txid_rdx1xjcqadt7nz052eps592pdz5mz0dnjv8x9r4ej7vysyz3288zsfzsr9jl3m';
// docs/PROJECT-STATE.md:2564.
const ESCROW_COMPONENT = 'component_rdx1cz468eqyr0fklyrlcsznadrwfnqnesw37vlm9j0xmq2s7427akd82f';
// docs/ESCROW-ADDRESSES.md:61 / docs/PROJECT-STATE.md:5709 — mainnet XRD, the fixed native resource.
const XRD_RESOURCE = 'resource_rdx1tknxxxxxxxxxradxrdxxxxxxxxx009923554798xxxxxxxxxradxrd';

async function main() {
  // Placeholder did:key identities: docs/PROJECT-STATE.md names the real
  // task's Radix account addresses (`…twekeqgp9`, `…t4mtg5q`), not Ed25519
  // did:keys, and this credential type's `poster`/`worker` fields are
  // did:keys — a real ceremony would derive these from the parties'
  // actual signing keys. For this self-dealt demo fixture, throwaway keys
  // stand in; README.md and the credential's own header say so plainly.
  const posterKey = await generateThrowawaySigningKey();
  const workerKey = await generateThrowawaySigningKey();

  const { credential, gatewayRead } = await buildCredentialFromReceipt(SETTLEMENT_TX, {
    task_id: 3,
    escrow_component: ESCROW_COMPONENT,
    network: 'mainnet',
    poster_did: publicKeyToDidKey(posterKey.publicKeyRaw),
    worker_did: publicKeyToDidKey(workerKey.publicKeyRaw),
    // docs/PROJECT-STATE.md:6414-6416 — SettlementCreditedEvent{worker_entitled: 10, poster_entitled: 11}.
    // This credential attests to the WORKER's settled payout (the reputation-relevant leg).
    amount_xrd: '10',
    resource: XRD_RESOURCE,
    outcome: 'dispute_resolved',
    // docs/PROJECT-STATE.md:6407/6411 — auto_resolve_dispute CommittedSuccess 2026-08-26T13:53:43Z.
    // For an already-disputed task, the terminal call's own commit is the point
    // of finality (there is no further review window after a resolved dispute).
    review_window_closed_at: '2026-08-26T13:53:43Z',
  });

  console.log(`Gateway (${DEFAULT_GATEWAY_URL}) read:`, gatewayRead);

  const fixturesDir = join(__dirname, 'fixtures');

  // The bare credential — exactly schema-shaped, nothing extra, so it can be
  // imported/verified/served as-is (e.g. by profile/credentials.json).
  writeFileSync(
    join(fixturesDir, 'unsigned-credential.task3.json'),
    JSON.stringify(credential, null, 2) + '\n'
  );

  // Its provenance, kept OUT of the credential object itself (canonicalizing
  // and signing operate over the whole credential minus `proofs`, so an
  // extra field here would silently become part of what a real signature
  // covers later — this file exists so that never has to happen).
  const provenance = {
    notice:
      'SELF-DEALT MECHANISM DEMO, NOT EVIDENCE. This unsigned credential describes a real ' +
      'settled Guild task, but every source is bigdev’s own documentation and every did:key ' +
      'is a throwaway demo key generated by this script — nobody has signed it, and the ' +
      'poster/worker DIDs are not the real task participants’ keys.',
    sources: [
      'docs/PROJECT-STATE.md:6407 (leg table) and :6398-6426 (narrative) — settlement_tx, outcome, timestamp',
      'docs/PROJECT-STATE.md:2564 — escrow_component',
      'docs/PROJECT-STATE.md:6414-6416 — SettlementCreditedEvent{worker_entitled: 10, poster_entitled: 11}; amount_xrd here is the worker’s leg',
      'docs/ESCROW-ADDRESSES.md:61 — resource (native XRD)',
    ],
    generatedAt: new Date().toISOString(),
    gatewayReadAttempt: gatewayRead,
  };
  writeFileSync(
    join(fixturesDir, 'unsigned-credential.task3.provenance.json'),
    JSON.stringify(provenance, null, 2) + '\n'
  );

  console.log('Wrote src/fixtures/unsigned-credential.task3.json + .provenance.json');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
