// public/openapi.json is generated by scripts/gen-openapi.mjs (catalogue P1-11) and gated in
// CI with `--check`. These tests pin the properties a language-agnostic client relies on:
// every /api/v1 route file is in the spec, every $ref resolves, session-gated operations
// declare the cookie scheme and a 401, and request bodies come from src/lib/validation.ts.
import { describe, it, expect } from "vitest"
import { readFileSync, readdirSync, statSync } from "node:fs"
import { join, relative, dirname, resolve } from "node:path"
import { MIN_REWARD_XRD } from "@/lib/marketplace"

const APP = resolve(__dirname, "../..")
const spec = JSON.parse(readFileSync(join(APP, "public/openapi.json"), "utf8"))
const ROUTES_DIR = join(APP, "src/app/api/v1")

function walk(dir: string): string[] {
  const out: string[] = []
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) out.push(...walk(p))
    else if (name === "route.ts") out.push(p)
  }
  return out
}

function toPath(file: string): string {
  const rel = relative(ROUTES_DIR, dirname(file)).split("\\").join("/")
  const p = "/" + rel.replace(/\[([^\]]+)\]/g, "{$1}")
  return p === "/." ? "/" : p
}

function collectRefs(node: unknown, acc: string[] = []): string[] {
  if (Array.isArray(node)) node.forEach((n) => collectRefs(n, acc))
  else if (node && typeof node === "object") {
    for (const [k, v] of Object.entries(node as Record<string, unknown>)) {
      if (k === "$ref" && typeof v === "string") acc.push(v)
      else collectRefs(v, acc)
    }
  }
  return acc
}

describe("public/openapi.json", () => {
  it("is OpenAPI 3.0 and points at the live server", () => {
    expect(spec.openapi).toMatch(/^3\.0\./)
    expect(spec.servers[0].url).toBe("https://radixguild.com/api/v1")
  })

  it("covers every /api/v1 route file in the tree", () => {
    const expected = walk(ROUTES_DIR).map(toPath)
    const missing = expected.filter((p) => !(p in spec.paths))
    expect(missing).toEqual([])
  })

  it("resolves every $ref inside components.schemas", () => {
    const refs = collectRefs(spec.paths)
    expect(refs.length).toBeGreaterThan(0)
    for (const ref of refs) {
      const name = ref.replace("#/components/schemas/", "")
      expect(spec.components.schemas[name], ref).toBeDefined()
    }
  })

  it("session-gated operations declare the cookie scheme and a 401", () => {
    let gated = 0
    for (const ops of Object.values(spec.paths) as Record<string, Record<string, unknown>>[]) {
      for (const op of Object.values(ops)) {
        const o = op as { security?: unknown[]; responses: Record<string, unknown> }
        if (o.security) {
          gated++
          expect(o.security).toEqual([{ sessionCookie: [] }])
          expect(o.responses["401"]).toBeDefined()
        }
      }
    }
    expect(gated).toBeGreaterThan(10)
    expect(spec.components.securitySchemes.sessionCookie.in).toBe("cookie")
  })

  it("derives request bodies from the validation schemas (POST /tasks = createTaskSchema)", () => {
    const post = spec.paths["/tasks"].post
    expect(post.requestBody.content["application/json"].schema.$ref).toBe("#/components/schemas/createTaskSchema")
    const body = spec.components.schemas.createTaskSchema
    expect(body.required).toEqual(expect.arrayContaining(["title", "description", "reward_amount"]))
    expect(body.properties.reward_amount.pattern).toBeDefined()
  })

  // The reward floor is a zod REFINEMENT, which has no JSON-Schema form: the
  // spec's `pattern` happily matches "0.5", a reward both routes answer with
  // 400 VALIDATION_ERROR (create_task reverts below the escrow's per-token
  // minimum). So the floor reaches a language-agnostic client only as the
  // property's description — this is the check that it still does, on BOTH
  // schemas that accept a reward. Falsifiable: drop `.describe(...)` from
  // validation.ts's rewardAmountSchema and regenerate the spec — `--check`
  // stays green (spec and schemas agree), and this is what goes red.
  it.each([["createTaskSchema"], ["updateTaskSchema"]])("%s.reward_amount documents the funded minimum", (schema) => {
    const description: unknown = spec.components.schemas[schema].properties.reward_amount.description
    expect(typeof description).toBe("string")
    expect(description).toContain(`at least ${MIN_REWARD_XRD}`)
    expect(description).toMatch(/VALIDATION_ERROR/)
  })
})
