"use strict";
// support-ai.js — /ask: a support answer grounded ONLY in the guild's own deployed
// docs, generated by a local Ollama model. Retrieval-first, cited, refuses outside
// the corpus, hands off to the existing /feedback ticket flow on request.
//
// This is a money-path product (on-chain escrow) — the guard rails matter more than
// the eloquence. In order, every /ask goes through:
//   1. a feature flag (default OFF)
//   2. input hygiene (length, seed-phrase / private-key refusal)
//   3. a per-user rolling rate limit + a global FIFO queue (concurrency 1 — one
//      small VPS should not run two local-model calls at once)
//   4. our own BM25 retrieval over a JSON corpus fetched from the dashboard —
//      below SUPPORT_AI_MIN_SCORE we never call the model at all
//   5. a single Ollama /api/chat call, told to answer ONLY from the numbered
//      passages it's given
//   6. an output guard that strips ungrounded addresses/URLs and replaces the
//      answer entirely if it looks too short or shares none of the retrieved
//      passages' most distinctive tokens
//
// We deliberately do NOT reuse faq-matcher.js's keyword table — those answers are
// hardcoded and stale (see CLAUDE.md). /ask replaces its role with something that
// answers from the live, deployed docs instead of a fixed list baked into this file.
//
// Everything stateful (corpus cache, rate limiter, queue) lives behind the
// createSupportAi(options) factory so tests can inject { db, fetch, now, env } —
// mirroring services/guards.js's createBanGuard/createThrottleGuard style.

const { InlineKeyboard } = require("grammy");

// ── Config ───────────────────────────────────────────────

const DEFAULTS = {
  OLLAMA_URL: "http://127.0.0.1:11434",
  SUPPORT_AI_MODEL: "qwen2.5:3b",
  SUPPORT_AI_MIN_SCORE: 2.0,
  SUPPORT_AI_TIMEOUT_MS: 90000,
  SUPPORT_AI_USER_LIMIT: 5,
  SUPPORT_AI_QUEUE_MAX: 5,
  RATE_WINDOW_MS: 10 * 60 * 1000, // "5 per 10 minutes" — the window itself isn't env-configurable
  CORPUS_TTL_MS: 60 * 60 * 1000, // cache the corpus for 1 hour
  CORPUS_FETCH_TIMEOUT_MS: 15000, // 15s corpus fetch timeout
};

function numOr(value, fallback) {
  if (value === undefined || value === null || value === "") return fallback;
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
}

function readConfig(env) {
  const portal = env.PORTAL_URL || "https://radixguild.com";
  return {
    enabled: String(env.SUPPORT_AI_ENABLED).toLowerCase() === "true",
    corpusUrl: env.SUPPORT_AI_CORPUS_URL || (portal + "/support-corpus.json"),
    ollamaUrl: env.OLLAMA_URL || DEFAULTS.OLLAMA_URL,
    model: env.SUPPORT_AI_MODEL || DEFAULTS.SUPPORT_AI_MODEL,
    minScore: numOr(env.SUPPORT_AI_MIN_SCORE, DEFAULTS.SUPPORT_AI_MIN_SCORE),
    timeoutMs: numOr(env.SUPPORT_AI_TIMEOUT_MS, DEFAULTS.SUPPORT_AI_TIMEOUT_MS),
    userLimit: numOr(env.SUPPORT_AI_USER_LIMIT, DEFAULTS.SUPPORT_AI_USER_LIMIT),
    queueMax: numOr(env.SUPPORT_AI_QUEUE_MAX, DEFAULTS.SUPPORT_AI_QUEUE_MAX),
  };
}

// ── Tokenizer + BM25 (k1 = 1.5, b = 0.75) ───────────────────

const STOPWORDS = new Set([
  "the", "a", "an", "and", "or", "but", "of", "to", "in", "on", "for", "is", "are",
  "was", "were", "be", "been", "being", "it", "its", "this", "that", "these", "those",
  "with", "as", "by", "at", "from", "how", "what", "when", "where", "why", "who",
  "which", "can", "do", "does", "did", "i", "you", "he", "she", "we", "they", "my",
  "your", "our", "their", "if", "not", "no", "so", "will", "would", "should", "could",
  "has", "have", "had", "into", "about", "up", "out", "than", "me", "us",
]);

function tokenize(text) {
  if (!text) return [];
  return String(text)
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((t) => t.length >= 2 && !STOPWORDS.has(t));
}

// Title tokens are included twice — a simple field boost so a question that
// matches a chunk's title ranks that chunk above one that only matches in body text.
function chunkTokens(chunk) {
  const titleToks = tokenize(chunk.title);
  return titleToks.concat(titleToks, tokenize(chunk.text));
}

function buildCorpusIndex(chunks) {
  const docs = (chunks || []).map((chunk) => {
    const tokens = chunkTokens(chunk);
    const tf = new Map();
    for (const t of tokens) tf.set(t, (tf.get(t) || 0) + 1);
    return { chunk, tf, length: tokens.length };
  });
  const N = docs.length;
  const df = new Map();
  for (const d of docs) {
    for (const t of d.tf.keys()) df.set(t, (df.get(t) || 0) + 1);
  }
  const avgdl = N ? docs.reduce((s, d) => s + d.length, 0) / N : 0;
  const idf = new Map();
  for (const [t, n] of df) idf.set(t, Math.log(1 + (N - n + 0.5) / (n + 0.5)));
  return { docs, idf, avgdl, N };
}

function scoreDoc(doc, queryTokens, idf, avgdl, k1, b) {
  let score = 0;
  for (const qt of queryTokens) {
    const f = doc.tf.get(qt) || 0;
    if (!f) continue;
    const idfVal = idf.get(qt) || 0;
    const denom = f + k1 * (1 - b + (b * doc.length) / (avgdl || 1));
    score += idfVal * ((f * (k1 + 1)) / denom);
  }
  return score;
}

// Returns { top: [{chunk, score}, ...] (best first, length <= topN), index, queryTokens }.
// `index` is exposed so callers (the output guard) can reuse the same corpus-wide idf
// without re-indexing.
function rankChunks(chunks, query, opts = {}) {
  const { k1 = 1.5, b = 0.75, topN = 3 } = opts;
  const index = buildCorpusIndex(chunks);
  const queryTokens = tokenize(query);
  const scored = index.docs.map((d) => ({
    chunk: d.chunk,
    score: scoreDoc(d, queryTokens, index.idf, index.avgdl, k1, b),
  }));
  scored.sort((a, c) => c.score - a.score);
  return { top: scored.slice(0, topN), index, queryTokens };
}

// The N tokens (from the retrieved passages only) with the highest corpus-wide idf —
// i.e. the most distinctive words those passages actually contain. Used by the output
// guard to catch a fluent-but-ungrounded answer that never touches what was retrieved.
function topInformativeTokens(passages, index, n = 10) {
  const seen = new Map(); // token -> idf
  for (const p of passages || []) {
    const doc = index.docs.find((d) => d.chunk.id === p.id);
    if (!doc) continue;
    for (const t of doc.tf.keys()) {
      if (!seen.has(t)) seen.set(t, index.idf.get(t) || 0);
    }
  }
  return [...seen.entries()]
    .sort((a, c) => c[1] - a[1])
    .slice(0, n)
    .map(([t]) => t);
}

// ── Input hygiene: seed phrases / private keys ──────────────

function looksLikePrivateKeyHex(text) {
  return /\b[0-9a-fA-F]{64,}\b/.test(text);
}

function looksLikeSeedPhrase(text) {
  const words = String(text).trim().split(/\s+/);
  let run = 0;
  for (const w of words) {
    if (/^[a-z]+$/.test(w)) {
      run++;
      if (run >= 12) return true;
    } else {
      run = 0;
    }
  }
  return false;
}

function detectSecret(text) {
  if (looksLikePrivateKeyHex(text)) return "hex_key";
  if (looksLikeSeedPhrase(text)) return "seed_phrase";
  return null;
}

// ── Corpus loader (fetch + 1h cache + last-good fallback) ───

// { builtAt, commit, pages, chunks: [{ id, page, url, title, text }] } served by the
// dashboard. Never invents an answer: if a refresh fails we serve the last good copy,
// and if there has never been a good copy the caller must refuse to answer at all.
function createCorpusStore({ fetchImpl, now, corpusUrl, fetchTimeoutMs, ttlMs }) {
  let cache = null; // { data, fetchedAt }
  let lastGood = null;

  async function fetchCorpus() {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), fetchTimeoutMs);
    try {
      const res = await fetchImpl(corpusUrl, { signal: ctrl.signal });
      if (!res.ok) throw new Error("corpus fetch HTTP " + res.status);
      const data = await res.json();
      if (!data || !Array.isArray(data.chunks)) throw new Error("corpus payload malformed");
      return data;
    } finally {
      clearTimeout(timer);
    }
  }

  return {
    async get() {
      const t = now();
      if (cache && t - cache.fetchedAt < ttlMs) return cache.data;
      try {
        const data = await fetchCorpus();
        cache = { data, fetchedAt: t };
        lastGood = cache;
        return data;
      } catch (e) {
        console.error("[support-ai] corpus refresh failed:", e.message);
        return lastGood ? lastGood.data : null;
      }
    },
    _debug() {
      return { cache, lastGood };
    },
  };
}

// ── Per-user rolling rate limit ──────────────────────────────

// Sliding-window log (not a fixed window) so "N per rolling 10 minutes" is exact.
function createRateLimiter({ limit = 5, windowMs = DEFAULTS.RATE_WINDOW_MS, now = Date.now } = {}) {
  const hits = new Map(); // tg_id -> [timestamp, ...] within the window

  return {
    check(tgId) {
      const t = now();
      if (hits.size > 5000) {
        for (const [k, arr] of hits) {
          if (!arr.length || t - arr[arr.length - 1] > windowMs) hits.delete(k);
        }
      }
      let arr = hits.get(tgId);
      if (!arr) {
        arr = [];
        hits.set(tgId, arr);
      }
      while (arr.length && t - arr[0] > windowMs) arr.shift();
      if (arr.length >= limit) {
        return { allowed: false, retryAfterMs: windowMs - (t - arr[0]) };
      }
      arr.push(t);
      return { allowed: true };
    },
    _hits: hits,
  };
}

// ── Global FIFO queue, concurrency 1 ─────────────────────────

function createRequestQueue({ max = 5, concurrency = 1 } = {}) {
  const waiting = [];
  let running = 0;

  function pump() {
    if (running >= concurrency) return;
    const next = waiting.shift();
    if (!next) return;
    running++;
    Promise.resolve()
      .then(next.task)
      .then(next.resolve, next.reject)
      .finally(() => {
        running--;
        pump();
      });
  }

  return {
    get size() {
      return waiting.length;
    },
    get running() {
      return running;
    },
    // { accepted: false } once `max` items are already waiting (the one item
    // actively running does not count against the cap). Otherwise
    // { accepted: true, result: <promise resolving with task()'s return value> }.
    submit(task) {
      if (waiting.length >= max) return { accepted: false };
      const result = new Promise((resolve, reject) => {
        waiting.push({ task, resolve, reject });
      });
      pump();
      return { accepted: true, result };
    },
  };
}

// ── Generation (Ollama /api/chat) ────────────────────────────

const SYSTEM_PROMPT =
  "You are the Radix Guild support assistant. Answer ONLY using the numbered " +
  "passages given below the question. If the passages do not contain the answer, " +
  "reply with exactly \"The docs don't cover that\" and nothing else.\n\n" +
  "Rules:\n" +
  "- Never state a wallet, component, resource, or package address.\n" +
  "- Never tell the user to send, transfer, or approve anything, or name an amount " +
  "to send — point them to the relevant page instead.\n" +
  "- No financial advice. No promises about outcomes or timing.\n" +
  "- At most 120 words. Plain text only, no markdown.\n" +
  "- End with one line: \"Sources: [n]\" listing the numbers of the passages you " +
  "actually used, e.g. \"Sources: [1, 3]\".";

function buildUserMessage(passages, question) {
  const numbered = passages
    .map((p, i) => (i + 1) + ". " + p.title + "\n" + p.text)
    .join("\n\n");
  return numbered + "\n\nQuestion: " + question;
}

async function callOllama({ fetchImpl, ollamaUrl, model, timeoutMs, passages, question }) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), timeoutMs);
  try {
    const res = await fetchImpl(ollamaUrl + "/api/chat", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model,
        stream: false,
        options: { temperature: 0.2, num_predict: 220, num_ctx: 4096 },
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: buildUserMessage(passages, question) },
        ],
      }),
      signal: ctrl.signal,
    });
    if (!res.ok) throw new Error("ollama HTTP " + res.status);
    const data = await res.json();
    const content = data && data.message && data.message.content;
    if (typeof content !== "string") throw new Error("ollama response missing message.content");
    return content;
  } finally {
    clearTimeout(timer);
  }
}

// ── Output guard ──────────────────────────────────────────

const NOT_COVERED_TEXT = "The docs don't cover that.";
const FOOTER = "AI answer from the guild's own docs. Verify on the linked pages before acting. Not financial advice.";
const ADDRESS_RE = /(account|component|resource|package)_(rdx|tdx)1[0-9a-z]+/gi;
const URL_RE = /https?:\/\/[^\s)\]]+/gi;

function passageHaystack(passages) {
  return passages.map((p) => (p.title || "") + "\n" + (p.text || "")).join("\n");
}

// (a) Strip any address-shaped token unless that exact string is present in one of
// the retrieved passages — the model has no business inventing or repeating a real
// account/component/resource/package address that isn't literally in front of it.
function stripUngroundedAddresses(text, passages) {
  const haystack = passageHaystack(passages);
  let fired = false;
  const cleaned = text.replace(ADDRESS_RE, (m) => {
    if (haystack.includes(m)) return m;
    fired = true;
    return "[address removed]";
  });
  return { text: cleaned, fired };
}

// (b) Strip any http(s) URL not present in the passages (title, text, or url field).
function stripForeignUrls(text, passages) {
  const haystack = passageHaystack(passages) + "\n" + passages.map((p) => p.url || "").join("\n");
  let fired = false;
  const cleaned = text.replace(URL_RE, (m) => {
    const trimmed = m.replace(/[.,;:!?]+$/, "");
    if (haystack.includes(m) || haystack.includes(trimmed)) return m;
    fired = true;
    return "[link removed]";
  });
  return { text: cleaned, fired };
}

function normalizeWhitespace(text) {
  return text
    .split("\n")
    .map((line) => line.replace(/[ \t]+/g, " ").trim())
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

// Applies (a)-(d) in order and returns { text, guard }. `guard` is a comma-joined
// list of the partial guards that fired ("address_stripped", "url_stripped", or
// "none"), UNLESS a full-replacement guard fired ("too_short" or "ungrounded"), in
// which case that name alone is returned since it supersedes any partial edits.
function applyOutputGuard(rawText, { passages, index, fallback = NOT_COVERED_TEXT }) {
  const fired = [];
  let text = rawText || "";

  const stripped1 = stripUngroundedAddresses(text, passages);
  text = stripped1.text;
  if (stripped1.fired) fired.push("address_stripped");

  const stripped2 = stripForeignUrls(text, passages);
  text = stripped2.text;
  if (stripped2.fired) fired.push("url_stripped");

  text = normalizeWhitespace(text);

  const wordCount = text ? text.split(/\s+/).filter(Boolean).length : 0;
  if (!text || wordCount < 8) {
    return { text: fallback, guard: "too_short" };
  }

  const informative = topInformativeTokens(passages, index, 10);
  const replyTokens = new Set(tokenize(text));
  const grounded = informative.length === 0 || informative.some((t) => replyTokens.has(t));
  if (!grounded) {
    return { text: fallback, guard: "ungrounded" };
  }

  return { text, guard: fired.length ? fired.join(",") : "none" };
}

// ── Reply assembly ───────────────────────────────────────────

// The model is asked to end its answer with "Sources: [n]" listing the passage
// numbers it used. Pulls that line out (wherever it lands) and returns the numbers
// separately so we render our OWN sources block with real titles/urls.
function extractCitedNumbers(text) {
  const lines = String(text || "").split("\n");
  let cited = null;
  const kept = [];
  for (const line of lines) {
    const m = /^\s*sources?\s*:\s*\[?\s*([0-9,\s]*)\]?\s*$/i.exec(line);
    if (m) {
      const nums = m[1]
        .split(",")
        .map((s) => parseInt(s.trim(), 10))
        .filter((n) => Number.isFinite(n));
      if (nums.length) cited = nums;
      continue;
    }
    kept.push(line);
  }
  return { body: kept.join("\n").trim(), cited };
}

// citedNumbers are 1-indexed positions into `passages` (as shown to the model).
// Falls back to all three passages when unparseable/empty. Dedupes by url.
function buildSourcesBlock(passages, citedNumbers) {
  let chosen = passages;
  if (Array.isArray(citedNumbers) && citedNumbers.length) {
    const picked = citedNumbers.map((n) => passages[n - 1]).filter(Boolean);
    if (picked.length) chosen = picked;
  }
  const seen = new Set();
  const lines = [];
  for (const p of chosen) {
    if (!p || seen.has(p.url)) continue;
    seen.add(p.url);
    lines.push("• " + p.title + " — " + p.url);
  }
  return lines.join("\n");
}

// ── Main factory ─────────────────────────────────────────────

function createSupportAi(options = {}) {
  const env = options.env || process.env;
  const fetchImpl = options.fetch || globalThis.fetch;
  const now = options.now || Date.now;
  const db = options.db;
  if (!db) throw new Error("createSupportAi requires options.db");

  const config = readConfig(env);
  const corpusStore = createCorpusStore({
    fetchImpl,
    now,
    corpusUrl: config.corpusUrl,
    fetchTimeoutMs: DEFAULTS.CORPUS_FETCH_TIMEOUT_MS,
    ttlMs: DEFAULTS.CORPUS_TTL_MS,
  });
  const rateLimiter = createRateLimiter({ limit: config.userLimit, windowMs: DEFAULTS.RATE_WINDOW_MS, now });
  const queue = createRequestQueue({ max: config.queueMax, concurrency: 1 });

  async function runAsk(ctx, question, tgId) {
    const startedAt = now();
    const corpus = await corpusStore.get();
    if (!corpus) return ctx.reply("The docs index is unavailable right now — see /support");

    const { top, index } = rankChunks(corpus.chunks, question, { k1: 1.5, b: 0.75, topN: 3 });
    const bestScore = top.length ? top[0].score : 0;

    if (!top.length || bestScore < config.minScore) {
      const latencyMs = now() - startedAt;
      const id = db.logSupportAi({
        tg_id: tgId, question, answer: NOT_COVERED_TEXT, sources: null,
        score: bestScore, model: null, latency_ms: latencyMs, guard: "below_threshold",
      });
      console.log("[support-ai] tg=" + tgId + " score=" + bestScore.toFixed(2) + " latency=" + latencyMs + " guard=below_threshold");
      const kb = new InlineKeyboard().text("👎 Open a ticket", "ai_ticket_" + id);
      return ctx.reply(NOT_COVERED_TEXT + " Try rephrasing, or open a support ticket.", { reply_markup: kb });
    }

    const passages = top.map((t) => t.chunk);
    try { await ctx.replyWithChatAction("typing"); } catch (_) { /* non-fatal */ }

    let rawModelText = "";
    let guardOverride = null;
    try {
      rawModelText = await callOllama({
        fetchImpl, ollamaUrl: config.ollamaUrl, model: config.model,
        timeoutMs: config.timeoutMs, passages, question,
      });
    } catch (e) {
      console.error("[support-ai] ollama call failed:", e.message);
      guardOverride = "model_error";
    }

    const { body, cited } = extractCitedNumbers(rawModelText || "");
    let finalText, guard;
    if (guardOverride) {
      finalText = NOT_COVERED_TEXT;
      guard = guardOverride;
    } else {
      const guarded = applyOutputGuard(body, { passages, index, fallback: NOT_COVERED_TEXT });
      finalText = guarded.text;
      guard = guarded.guard;
    }

    const sourcesBlock = buildSourcesBlock(passages, cited);
    const fullReply = finalText.trim() + "\n\nSources:\n" + sourcesBlock + "\n\n" + FOOTER;
    const latencyMs = now() - startedAt;

    const id = db.logSupportAi({
      tg_id: tgId, question, answer: finalText,
      sources: JSON.stringify(passages.map((p) => p.url)),
      score: bestScore, model: config.model, latency_ms: latencyMs, guard,
    });
    console.log("[support-ai] tg=" + tgId + " score=" + bestScore.toFixed(2) + " latency=" + latencyMs + " guard=" + guard);

    const kb = new InlineKeyboard()
      .text("👍 Helpful", "ai_helpful_" + id)
      .text("👎 Open a ticket", "ai_ticket_" + id);
    return ctx.reply(fullReply, { reply_markup: kb });
  }

  async function handleAsk(ctx) {
    if (!config.enabled) return ctx.reply("Not enabled yet — use /support");

    const raw = (ctx.message && ctx.message.text) || "";
    const question = raw.replace(/^\/ask(@\w+)?\s*/, "").trim();
    if (!question) {
      return ctx.reply("Usage: /ask <question>\n\nAsk anything about how the guild works — the answer is generated from the docs, with sources.");
    }
    if (question.length > 500) return ctx.reply("Question too long (max 500 chars). Please be concise.");

    // Refuse before any logging — never persist a pasted seed phrase or key.
    if (detectSecret(question)) {
      return ctx.reply("Never paste seed phrases or keys anywhere, including here.");
    }

    const tgId = ctx.from && ctx.from.id;
    const rl = rateLimiter.check(tgId);
    if (!rl.allowed) {
      const mins = Math.max(1, Math.ceil(rl.retryAfterMs / 60000));
      return ctx.reply("You've hit the /ask limit (" + config.userLimit + " per 10 min). Try again in " + mins + " minute" + (mins === 1 ? "" : "s") + ".");
    }

    const submission = queue.submit(() => runAsk(ctx, question, tgId));
    if (!submission.accepted) return ctx.reply("Busy — try again in a minute");
    return submission.result;
  }

  async function handleHelpfulCallback(ctx) {
    try {
      const m = /^ai_helpful_(\d+)$/.exec(ctx.callbackQuery.data);
      const id = m ? parseInt(m[1], 10) : NaN;
      if (Number.isFinite(id)) db.setSupportAiFeedback(id, "helpful");
      await ctx.answerCallbackQuery("Thanks for the feedback!");
      await ctx.editMessageText(ctx.callbackQuery.message.text + "\n\n👍 Marked helpful").catch(() => {});
    } catch (e) {
      console.error("[support-ai] helpful callback error:", e.message);
    }
  }

  async function handleTicketCallback(ctx) {
    try {
      const m = /^ai_ticket_(\d+)$/.exec(ctx.callbackQuery.data);
      const id = m ? parseInt(m[1], 10) : NaN;
      const row = Number.isFinite(id) ? db.getSupportAiLog(id) : null;
      const question = row ? row.question : "";
      const username = (ctx.from && (ctx.from.username || ctx.from.first_name)) || "anon";
      const ticketId = db.createFeedback(ctx.from.id, username, "[/ask] " + question);
      if (Number.isFinite(id)) db.setSupportAiFeedback(id, "ticket");
      await ctx.answerCallbackQuery("Ticket #" + ticketId + " created");
      await ctx.editMessageText(ctx.callbackQuery.message.text + "\n\nTicket #" + ticketId + " created. Check status: /mystatus").catch(() => {});
    } catch (e) {
      console.error("[support-ai] ticket callback error:", e.message);
    }
  }

  return {
    handleAsk,
    handleHelpfulCallback,
    handleTicketCallback,
    _internal: { corpusStore, rateLimiter, queue, config },
  };
}

module.exports = {
  createSupportAi,
  // Pure/testable pieces:
  tokenize,
  buildCorpusIndex,
  rankChunks,
  topInformativeTokens,
  detectSecret,
  looksLikeSeedPhrase,
  looksLikePrivateKeyHex,
  createCorpusStore,
  createRateLimiter,
  createRequestQueue,
  applyOutputGuard,
  extractCitedNumbers,
  buildSourcesBlock,
  DEFAULTS,
  SYSTEM_PROMPT,
  NOT_COVERED_TEXT,
  FOOTER,
};
